//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egzaminy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Egzamin
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public int CzasRozpoczecia { get; set; }
        public int CzasTrwania { get; set; }
        public int Sala { get; set; }
        public int Podgrupa { get; set; }
        [Display(Name ="Wyk³adowca")]
        public string id_wykladowcy { get; set; }
    
       // public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Podgrupa Podgrupa1 { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
