//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egzaminy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przedmioty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Przedmioty()
        {
            this.Rok = new HashSet<Rok>();
            this.Wykladowca = new HashSet<ApplicationUser>();
        }
    
        public int Id { get; set; }
        public string NazwaPrzedmiotu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rok> Rok { get; set; }
        public virtual ICollection<ApplicationUser> Wykladowca { get; set; }
    }
}
