//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egzaminy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rok()
        {
            this.Przedmioty = new HashSet<Przedmioty>();
            this.User = new HashSet<ApplicationUser>();
            this.Egzamin = new HashSet<Egzamin>();
        }
    
        public int Id { get; set; }
        public string NazwaRoku { get; set; }
    

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przedmioty> Przedmioty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationUser> User { get; set; }
        public virtual ICollection<Egzamin> Egzamin { get; set; }
    }
}
